name: Splunk AppInspect

on:
  push:
  pull_request:
    branches: [main]

jobs:
  appinspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package app
        run: |
          mkdir -p build
          rsync -rlt --progress . build/ta_nginx_ingress --exclude .git \
            --exclude .gitignore \
            --exclude .gitlab-ci.yml \
            --exclude build \
            --exclude .github \
            --exclude .appinspect.manualcheck.yaml
          cd build && tar czf ta_nginx_ingress.tar.gz ta_nginx_ingress
          shasum -a 256 ta_nginx_ingress.tar.gz > ta_nginx_ingress.tar.gz.sha256

      - uses: splunk/appinspect-cli-action@v1
        with:
          app_path: build/ta_nginx_ingress.tar.gz

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: appinspect-results
          path: appinspect_result.json
